import { afterEach, expect, test } from "bun:test";
import { mkdir, mkdtemp, readFile, rm } from "fs/promises";
import { tmpdir } from "os";
import { join } from "path";
import {
  getTerraformStateRemovalTargets,
  mergeVmConfigsWithExistingTfvars,
  parseManagedVmNamesFromTerraformStateList,
  parseVmConfigsFromTfvars,
  reconcileVmConfigsWithTerraformState,
  resolveTerraformProxmoxAuth,
  TerraformRunner,
} from "../../src/actions/helpers/terraform-runner";

const temporaryDirectories: string[] = [];

afterEach(async () => {
  await Promise.all(
    temporaryDirectories.splice(0).map((directory) =>
      rm(directory, { recursive: true, force: true })
    )
  );
});

test("parseVmConfigsFromTfvars reads generated vm_configs map", () => {
  const tfvars = `# Generated by Palindrome Action Layer
vm_bridge = "vmbr0"
use_ssh_agent = true
ssh_public_key = "ssh-ed25519 AAAA..."
cloud_init_datastore = "local"
vm_template_id = 8001

vm_configs = {
  "aba" = {
    target_node = "YANG"
    cores       = 2
    memory      = 4096
    disk_size   = "20G"
    vm_id       = 9000
  },
  "bib" = {
    target_node = "yin"
    cores       = 1
    memory      = 2048
    disk_size   = "10G"
    vm_id       = 9001
    template_id    = 8001
    ssh_username   = "m4"
    ssh_public_key = "ssh-ed25519 BBBB"
    datastore            = "fast-lvm"
    cloud_init_datastore = "local"
    vm_bridge            = "vmbr2"
    vlan_id              = 200
    bios                 = "ovmf"
    disk_interface       = "scsi0"
  }
}
`;

  const parsed = parseVmConfigsFromTfvars(tfvars);
  expect(Object.keys(parsed).sort()).toEqual(["aba", "bib"]);
  expect(parsed.aba).toEqual({
    target_node: "YANG",
    cores: 2,
    memory: 4096,
    disk_size: "20G",
    vm_id: 9000,
  });
  expect(parsed.bib).toEqual({
    target_node: "yin",
    cores: 1,
    memory: 2048,
    disk_size: "10G",
    vm_id: 9001,
    template_id: 8001,
    ssh_username: "m4",
    ssh_public_key: "ssh-ed25519 BBBB",
    datastore: "fast-lvm",
    cloud_init_datastore: "local",
    vm_bridge: "vmbr2",
    vlan_id: 200,
    bios: "ovmf",
    disk_interface: "scsi0",
  });
});

test("mergeVmConfigsWithExistingTfvars preserves existing VMs and upserts incoming VM", () => {
  const existingTfvars = `vm_configs = {
  "aba" = {
    target_node = "YANG"
    cores       = 2
    memory      = 4096
    disk_size   = "20G"
    vm_id       = 9000
  }
}
`;

  const merged = mergeVmConfigsWithExistingTfvars(existingTfvars, {
    bib: {
      target_node: "YANG",
      cores: 2,
      memory: 4096,
      disk_size: "20G",
      vm_id: 9001,
      template_id: 8001,
      ssh_username: "m4",
      ssh_public_key: "ssh-ed25519 BBBB",
    },
  });

  expect(Object.keys(merged).sort()).toEqual(["aba", "bib"]);
  expect(merged.aba?.vm_id).toBe(9000);
  expect(merged.bib?.vm_id).toBe(9001);
  expect(merged.bib?.template_id).toBe(8001);
  expect(merged.bib?.ssh_username).toBe("m4");
  expect(merged.bib?.ssh_public_key).toBe("ssh-ed25519 BBBB");
});

test("parseManagedVmNamesFromTerraformStateList reads only VM resources", () => {
  const stateList = `
proxmox_virtual_environment_file.cloud_config["pleas"]
proxmox_virtual_environment_vm.lab_vms["apple"]
proxmox_virtual_environment_vm.lab_vms["aha"]
null_resource.ansible_inventory
`;

  expect(Array.from(parseManagedVmNamesFromTerraformStateList(stateList)).sort()).toEqual(["aha", "apple"]);
});

test("getTerraformStateRemovalTargets includes orphaned cloud-config resources", () => {
  const stateList = `
proxmox_virtual_environment_file.cloud_config["apple"]
proxmox_virtual_environment_file.cloud_config["orphan"]
proxmox_virtual_environment_vm.lab_vms["apple"]
proxmox_virtual_environment_vm.lab_vms["target"]
`;

  expect(getTerraformStateRemovalTargets("target", stateList)).toEqual([
    'proxmox_virtual_environment_vm.lab_vms["target"]',
    'proxmox_virtual_environment_file.cloud_config["target"]',
    'proxmox_virtual_environment_file.cloud_config["orphan"]',
  ]);
});

test("reconcileVmConfigsWithTerraformState prunes stale tfvars entries absent from VM state", () => {
  const existingTfvars = `vm_configs = {
  "apple" = {
    target_node = "yin"
    cores       = 2
    memory      = 4096
    disk_size   = "20G"
    vm_id       = 9004
  }
  "pleas" = {
    target_node = "YANG"
    cores       = 2
    memory      = 4096
    disk_size   = "20G"
    vm_id       = 9005
  }
  "littlepally" = {
    target_node = "YANG"
    cores       = 2
    memory      = 4096
    disk_size   = "20G"
    vm_id       = 9000
  }
}
`;

  const { reconciledVmConfigs, removedVmNames } = reconcileVmConfigsWithTerraformState(
    existingTfvars,
    ["apple"],
    {
      aha: {
        target_node: "yin",
        cores: 2,
        memory: 4096,
        disk_size: "20G",
        vm_id: 9000,
      },
    }
  );

  expect(Object.keys(reconciledVmConfigs).sort()).toEqual(["apple"]);
  expect(removedVmNames.sort()).toEqual(["littlepally", "pleas"]);
});

test("resolveTerraformProxmoxAuth defaults yin to yin endpoint even when PROXMOX_URL points at yang", () => {
  const resolved = resolveTerraformProxmoxAuth("yin", {
    PROXMOX_URL: "https://yang.prox:8006",
    CLUSTER_TF_TOKEN_ID: "llm@pve!llm-agent",
    PROXMOX_CLUSTER_TF_SECRET: "cluster-secret",
  });

  expect(resolved.proxmoxUrl).toBe("https://yin.prox:8006");
  expect(resolved.tokenId).toBe("llm@pve!llm-agent");
  expect(resolved.tokenSecret).toBe("cluster-secret");
});

test("resolveTerraformProxmoxAuth prefers node-specific cluster endpoint and token pair", () => {
  const resolved = resolveTerraformProxmoxAuth("YANG", {
    PROXMOX_URL: "https://yin.prox:8006",
    PROXMOX_YANG_URL: "https://yang-custom.prox:8006",
    PROXMOX_YANG_TF_TOKEN_ID: "yang@pve!tf",
    PROXMOX_YANG_TF_SECRET: "yang-secret",
    CLUSTER_TF_TOKEN_ID: "llm@pve!llm-agent",
    PROXMOX_CLUSTER_TF_SECRET: "cluster-secret",
  });

  expect(resolved.proxmoxUrl).toBe("https://yang-custom.prox:8006");
  expect(resolved.tokenId).toBe("yang@pve!tf");
  expect(resolved.tokenSecret).toBe("yang-secret");
});

test("resolveTerraformProxmoxAuth defaults yang to yang endpoint", () => {
  const resolved = resolveTerraformProxmoxAuth("yang", {
    PROXMOX_URL: "https://yin.prox:8006",
    CLUSTER_TF_TOKEN_ID: "llm@pve!llm-agent",
    PROXMOX_CLUSTER_TF_SECRET: "cluster-secret",
  });

  expect(resolved.proxmoxUrl).toBe("https://yang.prox:8006");
});

test("TerraformRunner plan reads an isolated state without using unsupported state-out", async () => {
  const runner = new TerraformRunner();
  let capturedArgs: string[] = [];
  (runner as any).generateTfVars = async () => "/tmp/application.tfvars";
  (runner as any).executeTerraform = async (_command: string, args: string[]) => {
    capturedArgs = args;
    return { success: true, stdout: "", stderr: "" };
  };

  await runner.plan(
    { vmConfigs: {}, sshPublicKey: "ssh-ed25519 test" },
    { statePath: "/tmp/application.tfstate" }
  );

  expect(capturedArgs).toContain('-state="/tmp/application.tfstate"');
  expect(capturedArgs.some((arg) => arg.startsWith("-state-out="))).toBe(false);
});

test("TerraformRunner prunes requested and orphaned state resources", async () => {
  const runner = new TerraformRunner("/tmp/terraform-state-removal-test");
  const commands: Array<{ command: string; args: string[] }> = [];
  (runner as any).executeTerraform = async (command: string, args: string[]) => {
    commands.push({ command, args });
    if (args[0] === "list") {
      return {
        success: true,
        stdout: [
          'proxmox_virtual_environment_vm.lab_vms["apple"]',
          'proxmox_virtual_environment_file.cloud_config["apple"]',
          'proxmox_virtual_environment_file.cloud_config["orphan"]',
        ].join("\n"),
        stderr: "",
      };
    }
    return { success: true, stdout: "Removed", stderr: "" };
  };

  const result = await runner.removeVmFromState("apple", "/tmp/test.tfstate");

  expect(result.removed).toEqual([
    'proxmox_virtual_environment_vm.lab_vms["apple"]',
    'proxmox_virtual_environment_file.cloud_config["apple"]',
    'proxmox_virtual_environment_file.cloud_config["orphan"]',
  ]);
  expect(commands).toEqual([
    {
      command: "state",
      args: ["list", '-state="/tmp/test.tfstate"'],
    },
    {
      command: "state",
      args: [
        "rm",
        '-state="/tmp/test.tfstate"',
        `'proxmox_virtual_environment_vm.lab_vms["apple"]'`,
      ],
    },
    {
      command: "state",
      args: [
        "rm",
        '-state="/tmp/test.tfstate"',
        `'proxmox_virtual_environment_file.cloud_config["apple"]'`,
      ],
    },
    {
      command: "state",
      args: [
        "rm",
        '-state="/tmp/test.tfstate"',
        `'proxmox_virtual_environment_file.cloud_config["orphan"]'`,
      ],
    },
  ]);
});

test("TerraformRunner reconciles outputs and inventory after state removal", async () => {
  const root = await mkdtemp(join(tmpdir(), "terraform-reconcile-"));
  temporaryDirectories.push(root);
  const terraformDir = join(root, "terraform");
  const ansibleDir = join(root, "ansible");
  await mkdir(terraformDir);
  await mkdir(ansibleDir);
  const runner = new TerraformRunner(terraformDir);
  const commands: Array<{ command: string; args: string[] }> = [];
  (runner as any).executeTerraform = async (command: string, args: string[]) => {
    commands.push({ command, args });
    if (command === "output") {
      return {
        success: true,
        stdout: JSON.stringify({
          vm_info: {
            value: {
              apple: {
                name: "apple",
                node: "yin",
                id: 9004,
                hostname: "apple.prox",
                ip_addresses: ["172.16.0.44"],
              },
            },
          },
          vm_hostnames: { value: { apple: "apple.prox" } },
        }),
        stderr: "",
      };
    }
    return { success: true, stdout: "", stderr: "" };
  };

  const outputs = await runner.reconcileStateRemovalArtifacts({
    tfvarsPath: join(root, "palindrome.tfvars"),
  });
  const inventory = await readFile(join(ansibleDir, "inventory.ini"), "utf-8");

  expect(commands.map(({ command }) => command)).toEqual(["refresh", "output"]);
  expect(outputs.vm_hostnames).toEqual({ apple: "apple.prox" });
  expect(inventory).toContain("apple.prox ansible_host=apple.prox ansible_user=ops");
  expect(inventory).not.toContain("removed.prox");
});
