#!/bin/bash
# Diagnostic script for YANG token 401 error (Proxmox 8.4.1)
# Uses .prox domain for all network operations

echo "============================================================"
echo "YANG Token Diagnostic Commands (Proxmox 8.4.1)"
echo "============================================================"
echo ""
echo "All commands use .prox domain (yang.prox) for network operations"
echo ""
echo "Run these commands on YANG node (ssh root@yang.prox):"
echo ""
echo "1. Check if token exists:"
echo "   pveum user token list llm@pve"
echo ""
echo "2. Check token details (if it exists):"
echo "   pveum user token show llm@pve llm-agent"
echo ""
echo "3. Check user permissions:"
echo "   pveum user permissions llm@pve"
echo ""
echo "4. Check ACL permissions for token:"
echo "   pveum acl list | grep llm-agent"
echo ""
echo "5. Check if token was created on YANG (look for 'created' timestamp):"
echo "   pveum user token list llm@pve | grep -A 5 llm-agent"
echo ""
echo "6. Verify token secret matches .env:"
echo "   # On your local machine:"
echo "   grep PROXMOX_YANG_TF_SECRET .env"
echo "   # Compare with token secret from step 2"
echo ""
echo "============================================================"
echo "If token doesn't exist or secret is wrong:"
echo "============================================================"
echo ""
echo "1. Delete old token (if exists):"
echo "   pveum user token delete llm@pve llm-agent"
echo ""
echo "2. Create new token on YANG (Proxmox 8.4.1):"
echo "   pveum user token add llm@pve llm-agent --privsep 0"
echo ""
echo "3. Copy the token secret (displayed after creation) and update .env:"
echo "   PROXMOX_YANG_TF_SECRET=<new-secret-from-command-above>"
echo ""
echo "4. Verify token works using pvesh (Proxmox 8.4.1 API shell):"
echo "   pvesh get /version --token llm@pve!llm-agent=<secret>"
echo ""
echo "============================================================"
echo "Quick SSH command to run all checks (using yang.prox domain):"
echo "============================================================"
echo ""
echo "ssh root@yang.prox 'pveum user token list llm@pve && echo \"---\" && pveum user permissions llm@pve && echo \"---\" && pveum acl list | grep llm-agent'"
echo ""
echo "============================================================"
echo "Test token from local machine (using yang.prox domain):"
echo "============================================================"
echo ""
echo "# Load secret from .env and test (use single quotes to avoid bash history expansion):"
echo "SECRET=\$(grep PROXMOX_YANG_TF_SECRET .env | cut -d= -f2 | tr -d '\"')"
echo "curl -k -H 'Authorization: PVEAPIToken=llm@pve!llm-agent='\"\$SECRET\" https://yang.prox:8006/api2/json/version"
echo ""
echo "============================================================"
echo "IMPORTANT: Token Secret Mismatch Issue"
echo "============================================================"
echo ""
echo "In Proxmox clusters, each node generates its own secret for the same token ID."
echo "If the token was created on 'yin', the secret on 'YANG' will be DIFFERENT."
echo ""
echo "To fix the 401 error, you need to:"
echo "1. Get the token secret from YANG node (only shown when token is created)"
echo "2. Update PROXMOX_YANG_TF_SECRET in .env with YANG's secret"
echo ""
echo "OR recreate the token on YANG:"
echo "  ssh root@yang.prox 'pveum user token delete llm@pve llm-agent'"
echo "  ssh root@yang.prox 'pveum user token add llm@pve llm-agent --privsep 0'"
echo "  # Copy the secret shown and update .env"
echo ""
